/**
 * AI Story Generator for Dragon City
 * 
 * Generates dynamic story missions including:
 * - New dragon discoveries
 * - Dragon ridge creation events
 * - Chaos events (dragons out of control)
 * - Auto-evolving storylines
 */

export interface StoryMission {
  id: string;
  type: 'discovery' | 'ridge' | 'chaos' | 'evolution' | 'prophecy';
  title: string;
  description: string;
  storyText: string;
  objectives: StoryObjective[];
  rewards: StoryReward;
  difficulty: 'easy' | 'medium' | 'hard' | 'legendary';
  timeLimit?: number;
  unlockLevel: number;
  autoGenerated: boolean;
  createdAt: number;
  expiresAt?: number;
}

export interface StoryObjective {
  id: string;
  description: string;
  type: 'battle' | 'breed' | 'collect' | 'explore' | 'tame' | 'defend';
  target: number;
  current: number;
  completed: boolean;
}

export interface StoryReward {
  gold: number;
  gems: number;
  experience: number;
  dragonEgg?: {
    element: string;
    rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';
  };
  specialItem?: string;
}


const STORY_TEMPLATES = {
  discovery: [
    {
      title: "The Crystal Caverns Discovery",
      storyText: "Deep beneath the ancient mountains, tremors have revealed a hidden crystal cavern. Mysterious dragon eggs glow with an otherworldly light. Local villagers report hearing ethereal roars echoing from the depths.",
      objectives: [
        { type: 'explore', description: 'Explore the Crystal Caverns', target: 1 },
        { type: 'collect', description: 'Collect glowing crystals', target: 5 },
        { type: 'tame', description: 'Tame the discovered dragon', target: 1 }
      ],
      rewards: { gold: 1000, gems: 50, experience: 200, dragonEgg: { element: 'Crystal', rarity: 'epic' } }
    },
    {
      title: "Ancient Ruins Awakening",
      storyText: "Archaeologists have uncovered ruins containing dragon fossils that have begun to pulse with life energy. Something ancient is stirring, and it seeks worthy companions.",
      objectives: [
        { type: 'explore', description: 'Investigate the Ancient Ruins', target: 1 },
        { type: 'battle', description: 'Defeat guardian spirits', target: 3 },
        { type: 'breed', description: 'Awaken the ancient bloodline', target: 1 }
      ],
      rewards: { gold: 1500, gems: 75, experience: 300, dragonEgg: { element: 'Ancient', rarity: 'legendary' } }
    },
    {
      title: "The Starfall Event",
      storyText: "A meteor shower has brought celestial dragon eggs to your world. These cosmic beings possess powers never seen before. Act quickly before other trainers claim them!",
      objectives: [
        { type: 'collect', description: 'Collect starfall fragments', target: 10 },
        { type: 'explore', description: 'Locate crash sites', target: 3 },
        { type: 'tame', description: 'Bond with a celestial dragon', target: 1 }
      ],
      rewards: { gold: 2000, gems: 100, experience: 400, dragonEgg: { element: 'Celestial', rarity: 'mythic' } }
    }
  ],
  ridge: [
    {
      title: "Building Dragon's Peak",
      storyText: "The Dragon Council has tasked you with establishing a new dragon sanctuary on the highest mountain peak. This ridge will become home to rare mountain dragons and serve as a training ground for aerial combat.",
      objectives: [
        { type: 'collect', description: 'Gather mountain stone', target: 20 },
        { type: 'breed', description: 'Breed mountain-adapted dragons', target: 2 },
        { type: 'battle', description: 'Defend construction from rivals', target: 5 }
      ],
      rewards: { gold: 3000, gems: 150, experience: 500, specialItem: 'Mountain Ridge Deed' }
    },
    {
      title: "The Volcanic Sanctuary",
      storyText: "An active volcano has cooled just enough to support fire-type dragons. Create a ridge habitat in this treacherous environment to unlock the power of magma dragons.",
      objectives: [
        { type: 'explore', description: 'Survey the volcanic region', target: 1 },
        { type: 'collect', description: 'Collect obsidian shards', target: 15 },
        { type: 'tame', description: 'Tame volcanic guardian', target: 1 }
      ],
      rewards: { gold: 2500, gems: 125, experience: 450, dragonEgg: { element: 'Magma', rarity: 'legendary' } }
    },
    {
      title: "Ocean's Edge Establishment",
      storyText: "The tides have revealed a chain of islands perfect for water dragons. Establish a coastal ridge to unlock aquatic dragon breeding and naval combat abilities.",
      objectives: [
        { type: 'explore', description: 'Map the island chain', target: 5 },
        { type: 'breed', description: 'Breed aquatic dragons', target: 3 },
        { type: 'collect', description: 'Gather coral and pearls', target: 25 }
      ],
      rewards: { gold: 3500, gems: 175, experience: 600, specialItem: 'Tidal Ridge Blueprint' }
    }
  ],
  chaos: [
    {
      title: "The Rampage of Shadowflame",
      storyText: "A powerful legendary dragon has broken free from its containment. Shadowflame is rampaging through nearby villages, and only the strongest trainers can restore order. The Dragon Council is counting on you!",
      objectives: [
        { type: 'defend', description: 'Protect villages from attacks', target: 5 },
        { type: 'battle', description: 'Weaken Shadowflame in combat', target: 3 },
        { type: 'tame', description: 'Calm the rampaging dragon', target: 1 }
      ],
      rewards: { gold: 5000, gems: 250, experience: 1000, dragonEgg: { element: 'Shadow', rarity: 'mythic' } }
    },
    {
      title: "The Elemental Imbalance",
      storyText: "All elemental dragons have gone berserk! Fire and ice clash in violent storms, while earth and lightning dragons tear through the landscape. Restore balance before chaos consumes everything.",
      objectives: [
        { type: 'battle', description: 'Subdue fire dragons', target: 5 },
        { type: 'battle', description: 'Calm ice dragons', target: 5 },
        { type: 'tame', description: 'Restore elemental harmony', target: 4 }
      ],
      rewards: { gold: 7500, gems: 350, experience: 1500, specialItem: 'Elemental Crown' }
    },
    {
      title: "The Corrupted Hatchery",
      storyText: "A dark force has corrupted the main hatchery! Newly hatched dragons are emerging with twisted forms and aggressive temperaments. Stop the corruption before it spreads!",
      objectives: [
        { type: 'defend', description: 'Contain corrupted dragons', target: 10 },
        { type: 'battle', description: 'Defeat corruption source', target: 1 },
        { type: 'breed', description: 'Restore pure dragon bloodlines', target: 3 }
      ],
      rewards: { gold: 6000, gems: 300, experience: 1200, dragonEgg: { element: 'Pure', rarity: 'legendary' } }
    }
  ],
  evolution: [
    {
      title: "The Great Dragon Evolution",
      storyText: "Ancient prophecies speak of a great evolution event where dragons transcend their current forms. The stars align once every thousand years, and that time is NOW!",
      objectives: [
        { type: 'breed', description: 'Create evolved dragon pairs', target: 3 },
        { type: 'battle', description: 'Prove strength in evolution trials', target: 10 },
        { type: 'collect', description: 'Gather evolution stones', target: 30 }
      ],
      rewards: { gold: 10000, gems: 500, experience: 2000, specialItem: 'Evolution Crystal' }
    }
  ],
  prophecy: [
    {
      title: "The Dragon Prophecy Unfolds",
      storyText: "An ancient scroll reveals that a chosen trainer will unite the five legendary dragons and prevent an apocalyptic event. The prophecy points to YOU as the chosen one.",
      objectives: [
        { type: 'collect', description: 'Collect prophecy fragments', target: 5 },
        { type: 'battle', description: 'Defeat legendary guardians', target: 5 },
        { type: 'tame', description: 'Bond with legendary dragons', target: 5 }
      ],
      rewards: { gold: 15000, gems: 750, experience: 3000, dragonEgg: { element: 'Prophecy', rarity: 'mythic' } }
    }
  ]
};

/**
 * Story Progression State
 */
export class StoryProgressionManager {
  private currentChapter: number = 1;
  private discoveredDragons: Set<string> = new Set();
  private establishedRidges: Set<string> = new Set();
  private chaosEventsResolved: number = 0;
  private playerLevel: number = 1;

  /**
   * Generate a new story mission based on player progression
   */
  generateMission(playerLevel: number, forceType?: StoryMission['type']): StoryMission {
    this.playerLevel = playerLevel;
    
    // Determine mission type based on player level and progression
    let missionType: StoryMission['type'];
    
    if (forceType) {
      missionType = forceType;
    } else {
      missionType = this.selectMissionType();
    }

    // Get random template for this type
    const templates = STORY_TEMPLATES[missionType];
    const template = templates[Math.floor(Math.random() * templates.length)];

    // Generate unique mission
    const mission: StoryMission = {
      id: `story_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      type: missionType,
      title: template.title,
      description: this.generateDescription(missionType),
      storyText: template.storyText,
      objectives: template.objectives.map((obj, idx) => ({
        id: `obj_${idx}`,
        description: obj.description,
        type: obj.type as StoryObjective['type'],
        target: obj.target,
        current: 0,
        completed: false
      })),
      rewards: {
        gold: template.rewards.gold,
        gems: template.rewards.gems,
        experience: template.rewards.experience,
        dragonEgg: 'dragonEgg' in template.rewards && template.rewards.dragonEgg ? {
          element: template.rewards.dragonEgg.element,
          rarity: template.rewards.dragonEgg.rarity as 'common' | 'rare' | 'epic' | 'legendary' | 'mythic'
        } : undefined,
        specialItem: 'specialItem' in template.rewards ? template.rewards.specialItem : undefined
      },
      difficulty: this.calculateDifficulty(playerLevel, missionType),
      unlockLevel: Math.max(1, playerLevel - 5),
      autoGenerated: true,
      createdAt: Date.now(),
      expiresAt: missionType === 'chaos' ? Date.now() + (24 * 60 * 60 * 1000) : undefined // Chaos missions expire in 24h
    };

    return mission;
  }

  /**
   * Select mission type based on player progression
   */
  private selectMissionType(): StoryMission['type'] {
    const random = Math.random();
    
    // Early game: Focus on discovery
    if (this.playerLevel < 10) {
      return random < 0.7 ? 'discovery' : 'ridge';
    }
    
    // Mid game: Mix of everything
    if (this.playerLevel < 30) {
      if (random < 0.3) return 'discovery';
      if (random < 0.6) return 'ridge';
      if (random < 0.9) return 'chaos';
      return 'evolution';
    }
    
    // End game: More chaos and prophecy
    if (random < 0.2) return 'discovery';
    if (random < 0.4) return 'ridge';
    if (random < 0.7) return 'chaos';
    if (random < 0.9) return 'evolution';
    return 'prophecy';
  }

  /**
   * Calculate mission difficulty
   */
  private calculateDifficulty(playerLevel: number, type: StoryMission['type']): 'easy' | 'medium' | 'hard' | 'legendary' {
    if (type === 'prophecy') return 'legendary';
    if (type === 'chaos' || type === 'evolution') return 'hard';
    if (playerLevel < 10) return 'easy';
    if (playerLevel < 25) return 'medium';
    return 'hard';
  }

  /**
   * Generate contextual description
   */
  private generateDescription(type: StoryMission['type']): string {
    const descriptions = {
      discovery: "A new dragon species has been spotted! Investigate and add it to your collection.",
      ridge: "Expand your dragon empire by establishing a new ridge habitat.",
      chaos: "URGENT: Dragons are out of control! Restore order before it's too late!",
      evolution: "Rare opportunity: Evolve your dragons to their ultimate forms.",
      prophecy: "Ancient legends are coming true. You are the chosen one."
    };
    return descriptions[type];
  }

  /**
   * Generate multiple missions for mission board
   */
  generateMissionBatch(playerLevel: number, count: number = 3): StoryMission[] {
    const missions: StoryMission[] = [];
    
    for (let i = 0; i < count; i++) {
      missions.push(this.generateMission(playerLevel));
    }
    
    return missions;
  }

  /**
   * Check if mission should auto-spawn based on events
   */
  shouldSpawnChaosMission(dragonCount: number): boolean {
    // Spawn chaos mission if player has many dragons but hasn't resolved chaos recently
    return dragonCount > 20 && this.chaosEventsResolved < Math.floor(dragonCount / 20);
  }

  /**
   * Update progression based on completed mission
   */
  onMissionComplete(mission: StoryMission) {
    switch (mission.type) {
      case 'discovery':
        if (mission.rewards.dragonEgg) {
          this.discoveredDragons.add(mission.rewards.dragonEgg.element);
        }
        break;
      case 'ridge':
        this.establishedRidges.add(mission.id);
        break;
      case 'chaos':
        this.chaosEventsResolved++;
        break;
      case 'evolution':
      case 'prophecy':
        this.currentChapter++;
        break;
    }
  }

  /**
   * Get current story chapter for UI display
   */
  getCurrentChapter(): { number: number; title: string; description: string } {
    const chapters = [
      { number: 1, title: "The Beginning", description: "Your journey as a dragon trainer begins..." },
      { number: 2, title: "Rise to Power", description: "Your reputation grows across the land..." },
      { number: 3, title: "The Great Challenge", description: "Ancient forces stir in the shadows..." },
      { number: 4, title: "Legendary Awakening", description: "You stand among the greatest trainers..." },
      { number: 5, title: "The Final Prophecy", description: "The fate of all dragons rests in your hands..." }
    ];
    
    const chapterIndex = Math.min(this.currentChapter - 1, chapters.length - 1);
    return chapters[chapterIndex];
  }

  /**
   * Get stats for UI display
   */
  getProgressionStats() {
    return {
      chapter: this.currentChapter,
      uniqueDragonsDiscovered: this.discoveredDragons.size,
      ridgesEstablished: this.establishedRidges.size,
      chaosEventsResolved: this.chaosEventsResolved,
      totalStoryPoints: 
        (this.discoveredDragons.size * 100) +
        (this.establishedRidges.size * 200) +
        (this.chaosEventsResolved * 500) +
        (this.currentChapter * 1000)
    };
  }
}

/**
 * Singleton instance
 */
export const storyGenerator = new StoryProgressionManager();
